### ISSUE TITLE
Please add LICENSE file and headers

### ISSUE THREAD

**Issue by ktoso** [chrisaljoudi/swift-log-oslog#4]
Hi there,
thanks for the great LogHandler impl :-)

I wanted to check-in if you could add a license file.
Libraries without an explicit license are impossible to use in some environments.

Usually Apache v2 works well enough (it's also how most of the SSWG projects including swift-log are licensed ( https://github.com/apple/swift-log/blob/master/LICENSE.txt )). You can add a license quite easily using the helper: https://github.com/chrisaljoudi/swift-log-oslog/community/license/new?branch=master&template=apache-2.0

Ultimately it's your call which license to pick of course though 👍 

Thanks in advance!

**Comment by chrisaljoudi** [comment]
Done in 82896b6 — thanks @ktoso!

**Comment by ktoso** [comment]
Awesome, thanks a lot! 👍
