### ISSUE TITLE
New release with changes

### ISSUE THREAD

**Issue by txaiwieser** [chrisaljoudi/swift-log-oslog#5]
Hi, can we get a new version release? (tag)
We are having some problems with availability but it seems it was fixed on master already!

Thanks!

**Comment by chrisaljoudi** [comment]
[Just released 0.2.1](https://github.com/chrisaljoudi/swift-log-oslog/releases/tag/0.2.1). Thanks!

**Comment by txaiwieser** [comment]
Awesome! Thanks @chrisaljoudi
